Initializing Tensors

In [1]:
import torch

In [7]:
device = "cuda" if torch.cuda.is_available() else "cpu"

tensor = torch.tensor(([1, 2, 3], [4, 5, 6]), dtype=torch.float16, device=device, requires_grad=True) #cpu or cuda
print(tensor)
print(tensor.dtype)
print(tensor.shape)
print(tensor.device)
print(tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', dtype=torch.float16,
       requires_grad=True)
torch.float16
torch.Size([2, 3])
cuda:0
True


In [50]:
x = torch.empty((4,4))
x = torch.zeros((3,3))
x = torch.rand((3,3))
x = torch.ones((3,3))
x = torch.eye(5,5)
x = torch.arange(0, 5, 1) # 0, 1, 2, 3, 4
x = torch.linspace(0,5,5) # 0, 1.25, 2.5, 3.75, 5
x = torch.empty((1,5)).normal_(mean=0, std=1)
x = torch.empty((1,5)).uniform_(0,1) #uniform_(from=0, to=1)
x = torch.diag(torch.ones(3))

In [55]:
# convert tensor to other types (int, float, double)
tensor = torch.arange(4)
print(tensor.bool()) # True or False
print(tensor.short()) # int16
print(tensor.long()) #int64 (important)
print(tensor.half()) #float16
print(tensor.float()) #float32 (important)
print(tensor.double()) #float64

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [56]:
# array to tensor conversion and vice-versa
import numpy as np
np_array = np.zeros([5,5])
tensor = torch.from_numpy(np_array)
np_array_back = tensor.numpy()

Math & Comparison Operations

In [58]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])
# addition (add)
z1 = torch.empty(3)
torch.add(x, y, out=z1)
z2 = torch.add(x,y)
z = x + y

tensor([10., 10., 10.])

In [82]:
# substraction (sub)
z = x-y

# division
z = torch.true_divide(x,y)

# multiplies
torch.mul(x,y)

tensor([ 9, 16, 21])

In [72]:
# inplace operations
t = torch.zeros(3)
t.add_(x)
t += x # t = t + x

In [75]:
# Exponentiation
z = x.pow(2)
z = x ** 2

tensor([1, 4, 9])

In [78]:
# Simple Comparison
z = x > 0
z = x < 0
z

tensor([False, False, False])

In [81]:
# matrix multiplication
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))
x3 = torch.mm(x1,x2) #2,3
x3 = x1.mm(x2)
x3

tensor([[1.4494, 1.3573, 1.3242],
        [1.5820, 1.2177, 1.1714]])

In [86]:
# matrix exponentiation
matrix_exp = torch.rand(5,5)
print(matrix_exp)
matrix_exp.matrix_power(3)

tensor([[0.0885, 0.5685, 0.7099, 0.2875, 0.0995],
        [0.4176, 0.0095, 0.1323, 0.8523, 0.5170],
        [0.8162, 0.3118, 0.3683, 0.5084, 0.1702],
        [0.0666, 0.0987, 0.3461, 0.5744, 0.5664],
        [0.2483, 0.4694, 0.8606, 0.7418, 0.9996]])


tensor([[0.9453, 1.1110, 1.8528, 1.9934, 1.6823],
        [1.5057, 1.1416, 2.0069, 2.5710, 2.2047],
        [1.4922, 1.1399, 1.9422, 2.5231, 1.9986],
        [1.2732, 1.1409, 1.9687, 2.3295, 2.0327],
        [2.4658, 2.2888, 3.9037, 4.5685, 3.9093]])

In [87]:
# element wise mult
z = x * y
z

tensor([ 9, 16, 21])

In [88]:
# dot product
z = torch.dot(x,y)
z

tensor(46)

In [90]:
# Batch Matrix Multiplication
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2) # (batch, n, p)

In [95]:
# Example of Broadcasting
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))

z = x1-x2
print(z)
z = x1 **x2
print(x1)
print(x2)
print(z)

tensor([[ 0.3810,  0.2653,  0.1531, -0.7052, -0.4399],
        [ 0.5630, -0.1691,  0.0364, -0.6834,  0.3283],
        [ 0.2680,  0.0622, -0.1111, -0.7342, -0.1141],
        [ 0.6177, -0.5010,  0.3468, -0.1184, -0.3676],
        [ 0.2076,  0.0626, -0.0736, -0.7944,  0.2530]])
tensor([[0.7515, 0.8521, 0.3118, 0.2109, 0.1187],
        [0.9335, 0.4177, 0.1951, 0.2327, 0.8869],
        [0.6386, 0.6490, 0.0477, 0.1818, 0.4445],
        [0.9883, 0.0858, 0.5056, 0.7977, 0.1910],
        [0.5782, 0.6494, 0.0852, 0.1216, 0.8116]])
tensor([[0.3705, 0.5868, 0.1587, 0.9161, 0.5586]])
tensor([[0.8996, 0.9103, 0.8311, 0.2403, 0.3040],
        [0.9748, 0.5992, 0.7715, 0.2630, 0.9352],
        [0.8469, 0.7759, 0.6169, 0.2098, 0.6358],
        [0.9956, 0.2367, 0.8974, 0.8130, 0.3966],
        [0.8163, 0.7762, 0.6764, 0.1452, 0.8899]])


Indexing

Reshaping